export const eventTypes = [
    "Conference",
    "Seminar",
    "Workshop",
    "Trade Show",
    "Exhibition",
    "Networking Event",
    "Product Launch",
    "Awards Ceremony",
    "Charity Event",
    "Fundraiser",
    "Gala",
    "Meeting",
    "Webinar",
    "Training Session",
    "Lecture",
    "Screening",
    "Performance",
    "Concert",
    "Festival",
    "Fair",
    "Market",
    "Holiday Event",
    "Birthday Party",
    "Wedding",
    "Anniversary",
    "Graduation",
    "Retirement"
]